// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Modal$ReasonHasuraDemo from "./components/Modal.js";
import * as Header$ReasonHasuraDemo from "./components/Header.js";
import * as Counter$ReasonHasuraDemo from "./components/Counter.js";
import * as PostsList$ReasonHasuraDemo from "./components/PostsList.js";

function App(Props) {
  var match = React.useReducer((function (param, action) {
          if (action) {
            return /* record */[/* isModalOpened */false];
          } else {
            return /* record */[/* isModalOpened */true];
          }
        }), /* record */[/* isModalOpened */false]);
  var dispatch = match[1];
  var state = match[0];
  var match$1 = state[/* isModalOpened */0];
  return React.createElement("div", {
              onClick: (function (param) {
                  return Curry._1(dispatch, /* Close */1);
                })
            }, React.createElement(Header$ReasonHasuraDemo.make, {
                  openModal: (function (param) {
                      return Curry._1(dispatch, /* Open */0);
                    }),
                  isModalOpened: state[/* isModalOpened */0]
                }), match$1 ? React.createElement(Modal$ReasonHasuraDemo.make, {
                    closeModal: (function (param) {
                        return Curry._1(dispatch, /* Close */1);
                      })
                  }) : null, React.createElement(PostsList$ReasonHasuraDemo.make, { }), React.createElement(Counter$ReasonHasuraDemo.make, { }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
