// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReactApollo from "react-apollo";
import * as App$ReasonreactSimpleBlogCms from "./App.js";
import * as ApolloClient$ReasonreactSimpleBlogCms from "./ApolloClient.js";

import './App.css'
;

import 'animate.css'
;

ReactDOMRe.renderToElementWithId(React.createElement(ReactApollo.ApolloProvider, {
          client: ApolloClient$ReasonreactSimpleBlogCms.makeApolloClient(/* () */0),
          children: React.createElement(App$ReasonreactSimpleBlogCms.make, { })
        }), "root");

export {
  
}
/*  Not a pure module */
