// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReactApollo from "react-apollo";
import * as ServiceWorker from "./serviceWorker";
import * as App$ReasonHasuraDemo from "./App.js";
import * as ApolloClient$ReasonHasuraDemo from "./ApolloClient.js";

import './index.css'
;

import 'animate.css'
;

function register_service_worker(prim) {
  ServiceWorker.register();
  return /* () */0;
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  return /* () */0;
}

ReactDOMRe.renderToElementWithId(React.createElement(ReactApollo.ApolloProvider, {
          client: ApolloClient$ReasonHasuraDemo.makeApolloClient(/* () */0),
          children: React.createElement(App$ReasonHasuraDemo.make, { })
        }), "root");

ServiceWorker.unregister();

export {
  register_service_worker ,
  unregister_service_worker ,
  
}
/*  Not a pure module */
