// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Counter(Props) {
  var match = React.useReducer((function (state, action) {
          if (action) {
            var match = state[/* count */0];
            if (match !== 0) {
              return /* record */[/* count */state[/* count */0] - 1 | 0];
            } else {
              return /* record */[/* count */0];
            }
          } else {
            return /* record */[/* count */state[/* count */0] + 1 | 0];
          }
        }), /* record */[/* count */0]);
  var dispatch = match[1];
  return React.createElement("div", {
              className: "container"
            }, React.createElement("h3", {
                  className: "w-auto ml-10 text-2xl"
                }, String(match[0][/* count */0])), React.createElement("button", {
                  className: "button m-2 border p-2 shadow-md",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Inc */0);
                    })
                }, "+"), React.createElement("button", {
                  className: "button m-2 border p-2 shadow-md",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Dec */1);
                    })
                }, "-"));
}

var make = Counter;

export {
  make ,
  
}
/* react Not a pure module */
