// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

function DummyComponent(Props) {
  return React.createElement("div", undefined, "Text");
}

var make = DummyComponent;

export {
  make ,
  
}
/* react Not a pure module */
